### ISSUE TITLE
Support for cnpg-postgres

### ISSUE THREAD

**Issue by bustersg** [handyman5/karakeep-chart#1]
I can't seem to get karakeep to use my local cnpg-postgres db.
It keep asking to open Sqlite.
Does your helm support postgres?

error
```
/db_migrations/index.js:811
                throw new TypeError('Cannot open database because the directory does not exist');
                ^

TypeError: Cannot open database because the directory does not exist
    at new Database (/db_migrations/index.js:811:9)
    at /db_migrations/index.js:13002:16
    at /db_migrations/index.js:13063:3
    at Object.<anonymous> (/db_migrations/index.js:13066:12)
    at Module._compile (node:internal/modules/cjs/loader:1730:14)
    at Object..js (node:internal/modules/cjs/loader:1895:10)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
```

values.yaml
```
# SQLite
persistence: {}
  # enabled: true
  # existingClaim: claimName
  # accessMode: ReadWriteOnce
  # size: 10Gi
  # storageClass: -
  # annotations: {}
  # volume:
  #   name: data
  #   mountPath: /data

web:
  extraEnvFrom:
    - secretRef:
        name: karakeep-cnpg-url  # Updated cnpg-postgres over sqlite
  #extraEnv:
    #DATA_DIR: /data
    #DATABASE_URL: "postgres://karakeepUSER:PASSWORD@postgres-cluster-rw.postgresql-prod:5432/karakeep_DB"

database:
  type: postgresql
```
